apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: polyglot-commerce
data:
  ORDERS_DB_HOST: orders-db
  ORDERS_DB_PORT: "5432"
  ORDERS_DB_NAME: orders
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
