apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: polyglot-commerce
data:
  CATALOG_DB_HOST: catalog-db
  CATALOG_DB_PORT: "5432"
  CATALOG_DB_NAME: catalog
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/polyglot-commerce
