apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: polyglot-commerce
data:
  PAYMENTS_DB_HOST: payments-db
  PAYMENTS_DB_PORT: "5432"
  PAYMENTS_DB_NAME: payments
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
